---
title: "Assignment-5"
author: "TILAK KUMAR BONALA"
date: "2022-11-20"
output:
  pdf_document: default
  html_document: default
---



###Formulating AP-hub lp model problem

# Objective function 
min: 775x1 + 800x2 + 800x3 + 800x4 + 800x5 + 775x6 + 750x7;
# Constraints 
0 x1 + 1x2 + 1x3 + 1x4 + 1x5 + 1x6 + 0x7 >= 18;
0 x1 + 0x2 + 1x3 + 1x4 + 1x5 + 1x6 + 1x7 >= 27;
1 x1 + 0x2 + 0x3 + 1x4 + 1x5 + 1x6 + 1x7 >= 22;
1 x1 + 1x2 + 0x3 + 0x4 + 1x5 + 1x6 + 1x7 >= 26;
1 x1 + 1x2 + 1x3 + 0x4 + 0x5 + 1x6 + 1x7 >= 25;
1 x1 + 1x2 + 1x3 + 1x4 + 0x5 + 0x6 + 1x7 >= 21;
1 x1 + 1x2 + 1x3 + 1x4 + 1x5 + 0x6 + 0x7 >= 19;
x1 > 0;
x2 > 0;
x3 > 0;
x4 > 0;
x5 > 0;  
x6 > 0;
x7 > 0;
int x1, x2, x3, x4, x5, x6, x7;

```{r}
library(lpSolveAPI)
Workers <- read.lp("C:/Users/Hello/Downloads/Assign_6_11.lp")
Workers

```

#Solving Ap Hub lp model to find optimal numnber of workers in facility.

```{r}
solve(Workers)
get.objective(Workers)
get.variables(Workers)

```
##25675 is the total cost for workers

```{r}
shift_workers <- matrix(c(0,4,5,0,8,1,0,0,0,5,0,8,1,13,2,0,0,0,8,1,13,2,4,0,0,8,1,13,2,4,5,0,0,1,13,2,3,4,0,0,0,13,2,4,5,0,8,0,0), ncol=7,byrow=TRUE)
row.names(shift_workers) <- c('Sun','Mon','Tues','Wed','Thur','Fri','Sat')
colnames(shift_workers)<- c('Sun/Mon','Mon/Tues','Tues/Wed','Wed/Thur','Thur/Fri','Fri/Sat','Sat/Sun')
shift_workers
#Optimal solution to minimizes the total wage expense according to shift of workers in the factory in a week.
```

```{r}
rowSums(shift_workers)

#Total of workers according the scheduled shift in  each day to minimize the total cost of  wage expense. 
```


